#!/bin/bash

###################################################################################
## This file is part of bitonic-sort
##
## bitonic-sort is free software: you can redistribute it and#or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
##  bitonic-sort is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with bitonic-sort.  If not, see <http:##www.gnu.org#licenses#>.
##
##  Copyright 2013 Aaron Wilhelm
###################################################################################

script_list=( )
for n_proc in 1 2 4 8 16 32
do
    for s in 16 32 64 128
    do
        name="RUNp${n_proc}n${s}M"
        size=$[$s * 1000000]
        m4 -Dname=$name -Dnum_proc=$n_proc -Dsize=$size run.m4 > $name
        script_list+="$name "
    done
done

for script in ${script_list[0]}
do
    for (( i=0 ; i < 5 ; i++))
    do
        qsub $script
    done
done